spring.application.name=ecommerceProyect

spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_challenge
spring.datasource.username=postgres
spring.datasource.password=Ray_skate105
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080