#Comment this section to disable database local configuration
spring.application.name=ecommerceProyect

spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_challenge
spring.datasource.username=postgres
spring.datasource.password=Ray_skate105
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

#Uncomment to work with docker containters
#spring.application.name=ecommerce-challenge
#
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_challenge}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#
#server.port=8080
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB